export default {
  RECEIVE_PEOPLE: 'RECEIVE_PEOPLE',
  RECEIVE_FILMS: 'RECEIVE_FILMS',
  RECEIVE_STARSHIPS: 'RECEIVE_STARSHIPS',
  RECEIVE_VEHICLES: 'RECEIVE_VEHICLES',
  RECEIVE_SPECIES: 'RECEIVE_SPECIES',
  RECEIVE_PLANETS: 'RECEIVE_PLANETS'
};
